services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: desafio_app
        restart: always
        command: bash -c 'php artisan migrate && php artisan serve --host=0.0.0.0'
        ports:
            -   '9000:8000'
        volumes:
            -   .:/var/www/html
        depends_on:
            - mysql
            - socket
        networks:
            - event-network

    nginx:
        image: nginx:latest
        container_name: desafio_nginx
        restart: always
        ports:
            - '8080:80'
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - event-network


    socket:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        container_name: desafio_socket
        restart: always
        ports:
            - '6001:6001'
            - '9601:9601'
        networks:
            - event-network

    mysql:
        container_name: desafio_db
        restart: always
        image: mysql:latest
        platform: linux/x86_64
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_USER: 'desafio'
            MYSQL_PASS: 'desafio'

        volumes:
            - ./db-data:/var/lib/mysql
        networks:
            - event-network
networks:
    event-network:
        driver: bridge
